import type { Product } from './catalogue';

const brochure =
  'https://chemstock.com/wp-content/uploads/2022/09/Chemstock-Brochure-.pdf';

type Group = {
  family: string;
  industries: string[];
  applications: string[];
  names: [string, ...string[]][];
};

const groups: Group[] = [
  {
    family: 'Acrylates and methacrylates',
    industries: ['coatings', 'plastics', 'industrial'],
    applications: [
      'Coatings and adhesives',
      'Polymer and resin production',
      'Specialty formulation',
    ],
    names: [
      ['Dipropylene Glycol Diacrylate', 'DPGDA'],
      ['Butyl Methacrylate', 'BMA'],
      ['Butyl Acrylate', 'N-Butyl Acrylate', 'BA'],
      ['Dimethylaminoethyl Methacrylate', 'DMAEMA'],
      ['Dimethylaminopropyl Methacrylamide', 'DMAPMA'],
      ['Ethylene Glycol Dimethacrylate', 'EGDMA'],
      ['2-Ethylhexyl Methacrylate', 'EHMA'],
      ['Ethoxylated Trimethylolpropane Triacrylate', 'EO3TMPTA'],
      ['1,6-Hexanediol Diacrylate', 'HDDA'],
      ['Hydroxyethyl Acrylate', 'HEA'],
      ['Hydroxyethyl Methacrylate', 'HEMA'],
      ['Hydroxypropyl Acrylate', 'HPA'],
      ['Hydroxypropyl Methacrylate', 'HPMA'],
      ['Isobutyl Methacrylate', 'IBMA'],
      ['Isobornyl Acrylate', 'IBOA'],
      ['Isobornyl Methacrylate', 'IBOMA'],
      ['tert-Butyl Acrylate', 'TBA'],
      ['Trimethylolpropane Triacrylate', 'TMPTA'],
      ['2-Ethylhexyl Acrylate', '2-EHA'],
      ['Acrylic Acid'],
    ],
  },
  {
    family: 'Aromatic and heterocyclic intermediates',
    industries: ['coatings', 'industrial'],
    applications: [
      'Chemical intermediates',
      'Resin and coating chemistry',
      'Specialty synthesis',
    ],
    names: [
      ['Imidazole'],
      ['p-Toluic Acid', '4-Methylbenzoic acid'],
      ['m-Toluic Acid', '3-Methylbenzoic acid'],
      ['o-Cresol', 'Ortho-cresol'],
      ['m-Aminophenol', 'Meta-aminophenol'],
      ['p-Aminophenol', 'Para-aminophenol'],
      ['p-tert-Butylphenol', 'PTBP'],
      ['o-Chloroaniline'],
    ],
  },
  {
    family: 'Silanes and coupling agents',
    industries: ['coatings', 'plastics', 'industrial'],
    applications: [
      'Silane coupling',
      'Sealants and coatings',
      'Surface treatment',
    ],
    names: [
      ['1,2-Bis(triethoxysilyl)ethane'],
      ['Di-tert-butoxydiacetoxysilane'],
      ['Ethyltriacetoxysilane'],
      ['Methyltriacetoxysilane'],
      ['Methyltriethoxysilane'],
      ['Methyltris(methylethylketoxime)silane'],
      ['Phenyltrimethoxysilane'],
      ['Phenyltris(methylethylketoxime)silane'],
      ['Tetraethylsilane'],
      ['Tetrapropoxysilane'],
      ['Vinyltris(methylethylketoxime)silane'],
      ['2-(3,4-Epoxycyclohexyl)ethyltrimethoxysilane'],
      ['3-Chloropropyldimethoxymethylsilane'],
      ['N-(2-Aminoethyl)-3-aminopropyltrimethoxysilane'],
      ['Trimethoxysilane'],
      ['3-Aminopropylmethyldiethoxysilane'],
      ['3-Aminopropyltriethoxysilane'],
      ['3-Aminopropyltrimethoxysilane'],
      ['3-Mercaptopropyltrimethoxysilane'],
      ['3-Mercaptopropyltriethoxysilane'],
      ['3-Methacryloxypropyltrimethoxysilane'],
    ],
  },
  {
    family: 'Plasticizers',
    industries: ['plastics', 'industrial', 'coatings'],
    applications: [
      'PVC and flexible polymers',
      'Resin modification',
      'Industrial plasticizer systems',
    ],
    names: [
      ['Diethyl Phthalate', 'DEP'],
      ['Dioctyl Terephthalate', 'DOTP'],
      ['Trioctyl Trimellitate', 'TOTM'],
      ['2-Octanol'],
      ['Diallyl Phthalate', 'DAP'],
      ['Dibutyl Phthalate', 'DBP'],
      ['Dicapryl Adipate / Sebacate', 'DCA', 'DCS'],
      ['Diisooctyl 2-Cyclohexanedicarboxylate', 'DHEH'],
      ['DHIN Plasticizer'],
      ['Diisobutyl Adipate', 'DIBA'],
      ['Diisobutyl Phthalate', 'DIBP'],
      ['Dimethyl Adipate', 'DMA'],
      ['Dimethyl Phthalate', 'DMP'],
      ['Dioctyl Adipate', 'DOA'],
      ['Di(2-propylheptyl) Phthalate', 'DPHP'],
      ['Trioctyl Phosphate', 'TOP'],
      ['2,2,4-Trimethyl-1,3-pentanediol Diisobutyrate', 'TXIB'],
    ],
  },
  {
    family: 'Chemical intermediates',
    industries: ['industrial', 'coatings', 'plastics'],
    applications: [
      'Chemical intermediates',
      'Resins and coatings',
      'Industrial formulation',
    ],
    names: [
      ['Phthalic Anhydride'],
      ['Maleic Anhydride'],
      ['Trimellitic Anhydride', 'TMA'],
      ['Adipic Acid'],
      ['Azelaic Acid'],
      ['Dodecanedioic Acid', 'DDDA'],
      ['Undecanedioic Acid', 'UDDA'],
      ['Brassylic Acid'],
      ['Dimer Acid'],
      ['Fumaric Acid'],
      ['Malic Acid'],
      ['Oxalic Acid'],
      ['Propionic Acid'],
      ['Citric Acid, Anhydrous'],
      ['Boric Acid'],
      ['Isocyanuric Acid'],
      ['Benzoguanamine'],
      ['Benzophenone'],
      ['Benzyl Acetate'],
      ['Benzyl Benzoate'],
      ['Butyl Benzoate'],
      ['1,4-Cyclohexanedimethanol', 'CHDM'],
      ['Trimethylolpropane', 'TMP'],
      ['Triacetin'],
      ['Trimethyl Orthoformate'],
      ['N-Methylbenzylamine'],
      ['Morpholine'],
      ['O/P-Toluene Sulfonamide', 'O/PTSA'],
      ['n-Propyl Bromide / Ethyl Bromide'],
      ['N-(n-Butyl)thiophosphoric Triamide', 'NBPT'],
    ],
  },
  {
    family: 'Rubber accelerators',
    industries: ['plastics', 'industrial'],
    applications: [
      'Rubber compounding',
      'Vulcanization systems',
      'Elastomer production',
    ],
    names: [
      ['Rubber Accelerator CBS', 'CZ'],
      ['Rubber Accelerator DBTU'],
      ['Rubber Accelerator DCBS', 'DZ'],
      ['Rubber Accelerator DETU'],
      ['Rubber Accelerator DOTG'],
      ['Rubber Accelerator DPG'],
      ['Rubber Accelerator DPTU'],
      ['Rubber Accelerator DTDM'],
      ['Rubber Accelerator ETU', 'NA-22'],
      ['Rubber Accelerator MBT', 'M'],
      ['Rubber Accelerator MBTS', 'DM'],
      ['Rubber Accelerator TBBS', 'NS'],
      ['Rubber Accelerator TBzTD'],
      ['Rubber Accelerator TETD'],
      ['Rubber Accelerator TMTD'],
      ['Rubber Accelerator TMTM'],
      ['Rubber Accelerator ZDBC', 'BZ'],
      ['Rubber Accelerator ZDEC', 'ZDC'],
      ['Rubber Accelerator ZDMC', 'PZ'],
    ],
  },
  {
    family: 'Epoxy reactive diluents',
    industries: ['coatings', 'industrial'],
    applications: [
      'Epoxy formulation',
      'Reactive dilution',
      'Resin modification',
    ],
    names: [
      ['C12–14 Alkyl Glycidyl Ether', 'C12-14 AGE'],
      ['1,6-Hexanediol Diglycidyl Ether', '1,6-HDGE'],
      ['1,4-Butanediol Diglycidyl Ether', '1,4-BDO DGE'],
      ['2-Ethylhexyl Glycidyl Ether'],
      ['Allyl Glycidyl Ether'],
      ['Butyl Glycidyl Ether', 'BGE'],
      ['Castor Oil Polyglycidyl Ether'],
      ['Hydrogenated Bisphenol-A Diglycidyl Ether', 'HBPADGE'],
      ['Neodecanoic Acid Glycidyl Ester', 'NDGE'],
      ['Neopentyl Glycol Diglycidyl Ether', 'NPDGE'],
      ['o-Cresyl Glycidyl Ether', 'o-CGE'],
      ['Resorcinol Diglycidyl Ether', 'RDGE'],
      ['Trimethylolpropane Triglycidyl Ether'],
    ],
  },
  {
    family: 'Polyether amines',
    industries: ['coatings', 'industrial'],
    applications: [
      'Epoxy curing',
      'Polyurea and resin systems',
      'Specialty amine chemistry',
    ],
    names: [
      ['Polyetheramine D-230'],
      ['Polyetheramine D-400'],
      ['Polyetheramine D-2000'],
      ['Polyetheramine T-403'],
      ['Polyetheramine T-5000'],
    ],
  },
  {
    family: 'Water-treatment additives',
    industries: ['industrial', 'oil-gas'],
    applications: [
      'Water treatment',
      'Corrosion and scale control',
      'Industrial process systems',
    ],
    names: [
      ['Acrylic Homopolymer KR-1000'],
      ['2-Phosphonobutane-1,2,4-tricarboxylic Acid', 'PBTC', 'PBCTA'],
      ['Sodium Benzotriazole 50%'],
      ['Sodium Tolytriazole 50%'],
      ['Sodium Fluorosilicate, NSF Grade', 'SSF'],
    ],
  },
  {
    family: 'Epoxy curing agents',
    industries: ['coatings', 'industrial'],
    applications: [
      'Epoxy curing',
      'Crosslinking',
      'Coatings and composite resins',
    ],
    names: [
      ['Tris(dimethylaminomethyl)phenol', 'DMP-30', 'K54'],
      ['Mixed MHHPA / MTHPA / HHPA', 'AMH-100'],
      ['N,N-Dimethylbenzylamine', 'BDMA'],
      ['Polyfunctional Aziridine Crosslinker', 'Crosslinker 100'],
      ['Diethyltoluenediamine', 'DETDA'],
      ['Dimethylthiotoluenediamine', 'DMTDA'],
      ['Hexahydrophthalic Anhydride', 'HHPA'],
      ['Methylhexahydrophthalic Anhydride', 'MHHPA'],
      ["4,4'-Methylenebis(2-ethylbenzenamine)", 'MOBEA'],
      ['Methyltetrahydrophthalic Anhydride', 'MTHPA'],
      ['Tetrahydrophthalic Anhydride', 'THPA'],
    ],
  },
  {
    family: 'Resins',
    industries: ['coatings', 'plastics', 'industrial'],
    applications: [
      'Coatings and adhesives',
      'Epoxy systems',
      'Polyaspartic and acrylic resin systems',
    ],
    names: [
      ['Epoxy Resin 827'],
      ['Epoxy Resin 828'],
      ['Epoxy Resin 1001, 75% Solution'],
      ['Epoxy Resin 8132'],
      ['Aldehyde Resin A81'],
      ['Liquid Bisphenol-A Epoxy Resin'],
      ['Novolac Epoxy Resin 638'],
      ['Polyaspartic Polyurea Resin 420'],
      ['Polyaspartic Polyurea Resin 520'],
      ['Solid Acrylic Resin B66'],
      ['Solid Acrylic Resin B-99N'],
      ['Solid Acrylic Resin DM55'],
      ['Solid Epoxy Resin 1001'],
      ['Solid Epoxy Resin 1004'],
      ['Solid Epoxy Resin 1007'],
      ['Solid Epoxy Resin 1009'],
    ],
  },
  {
    family: 'Food, pharmaceutical and personal-care ingredients',
    industries: ['food', 'personal-care', 'industrial'],
    applications: [
      'Food and beverage formulations',
      'Personal care',
      'Pharmaceutical formulation',
    ],
    names: [
      ['Benzyl Alcohol, USP / Kosher'],
      ['Castor Oil'],
      ['Disodium Phosphate'],
      ['Glycerine', 'Glycerol'],
      ['Monosodium Phosphate'],
      ['Stearyl Alcohol'],
      ['Erythorbic Acid, FCC IV / Kosher'],
      ['Ethyl Lactate, FCC Grade'],
      ['Sodium Erythorbate, FCC IV / Kosher'],
    ],
  },
  {
    family: 'Flame retardants',
    industries: ['plastics', 'coatings', 'industrial'],
    applications: [
      'Flame-retardant formulations',
      'Polymer compounds',
      'Coatings and resins',
    ],
    names: [
      ['Ammonium Polyphosphate', 'APP'],
      ['Bisphenol-A Bis(diphenyl phosphate)', 'BDP'],
      ['9,10-Dihydro-9-oxa-10-phosphaphenanthrene-10-oxide', 'DOPO'],
      ['Isopropylated Triphenyl Phosphate', 'IPPP'],
      ['Melamine Polyphosphate', 'MPP'],
      ['Tributoxyethyl Phosphate', 'TBEP'],
      ['Tricresyl Phosphate', 'TCP'],
      ['Tris(1,3-dichloro-2-propyl) Phosphate', 'TDCPP', 'TDCP'],
      ['Triethyl Phosphate', 'TEP'],
      ['Brominated Epoxy Resin'],
      ['Melamine Cyanurate'],
      ['Zinc Borate'],
      ['Brominated Flame Retardants, Source-Specific'],
    ],
  },
  {
    family: 'Pigments and minerals',
    industries: ['coatings', 'plastics', 'industrial'],
    applications: ['Pigments', 'Polymer compounding', 'Coatings'],
    names: [
      ['Titanium Dioxide, Rutile'],
      ['Titanium Dioxide, Anatase'],
      ['Zirconium Silicate'],
    ],
  },
  {
    family: 'Solvents and process fluids',
    industries: ['coatings', 'industrial', 'oil-gas'],
    applications: [
      'Solvent systems',
      'Cleaning and processing',
      'Coatings and resin formulation',
    ],
    names: [
      ['1,2-Diaminocyclohexane'],
      ['1,4-Butanediol', '1,4-BDO'],
      ['1,6-Hexanediol'],
      ['Acetonitrile, HPLC / Industrial Grade'],
      ['Acetylacetone'],
      ['Benzonitrile'],
      ['Benzotrifluoride', 'BTF'],
      ['Butyl Acetate'],
      ['Dibasic Ester', 'DBE'],
      ['Dicyclohexylamine', 'DCHA'],
      ['2,6-Dimethyl-4-heptanone', 'DIBK'],
      ['Diethylene Glycol Dimethyl Ether', 'Glycol Ether DM'],
      ['Dimethyl Carbonate', 'DMC'],
      ['Dipropylene Glycol Monomethyl Ether', 'DPM'],
      ['2-Butoxyethanol', 'Glycol Ether EB'],
      ['Ethylene Glycol Diacetate', 'EGDA', 'EGDE'],
      ['Ethyl 3-Ethoxypropionate', 'EEP'],
      ['Propylene Glycol n-Propyl Ether', 'Glycol Ether PnP'],
      ['Isopropyl Alcohol', 'IPA'],
      ['Methyl Ethyl Ketone', 'MEK'],
      ['Methyl Acetate'],
      ['N-Butyl Acetate', 'NBAC'],
      ['N-Methyl-2-pyrrolidone', 'NMP'],
      ['Nonylphenol'],
      ['p-Chlorobenzotrifluoride', 'PCBTF'],
      ['Propylene Glycol Methyl Ether Acetate', 'PMA'],
      ['Propylene Carbonate'],
      ['tert-Butyl Acetate', 'TBAC'],
      ['n-Heptane'],
    ],
  },
  {
    family: 'Industrial inorganic chemicals',
    industries: ['industrial', 'oil-gas'],
    applications: [
      'Industrial processing',
      'Cleaning and water treatment',
      'Formulation raw materials',
    ],
    names: [
      ['Ammonium Bifluoride'],
      ['Borax, 5 Mol'],
      ['Borax, 10 Mol'],
      ['Caustic Soda, Dry'],
      ['Caustic Soda, Flake'],
      ['Caustic Soda, 50%'],
      ['Hexametaphosphate'],
      ['Paraformaldehyde'],
      ['Hexamine, Prills'],
      ['Sodium Metasilicate'],
      ['Sodium Sulfite'],
      ['Sodium Thiosulfate'],
      ['Sodium Tripolyphosphate'],
      ['Tetrapotassium Pyrophosphate', 'TKPP'],
      ['Urea'],
      ['Barium Hydroxide, Monohydrate / Octahydrate'],
      ['Potassium Hydroxide, Flake', 'KOH Flake'],
      ['Potassium Hydroxide, 45% Liquid', 'KOH 45%'],
      ['Sodium Chlorate'],
      ['Sodium Formate'],
      ['Sodium Gluconate'],
      ['Sodium Metabisulfate'],
      ['Sodium Nitrate'],
      ['Sodium Percarbonate'],
      ['Sulfuric Acid'],
      ['Monoaluminum Phosphate'],
    ],
  },
  {
    family: 'Specialty additives and polymers',
    industries: ['coatings', 'plastics', 'industrial'],
    applications: [
      'Polymer additives',
      'Industrial formulations',
      'Specialty materials',
    ],
    names: [
      ['Dimethyl Silicone'],
      ['Ethylene Bis Stearamide', 'EBS'],
      ['Ethylene-Vinyl Acetate Copolymer', 'EVA'],
      ['Polyvinylpyrrolidone', 'PVP'],
      ['C8–C10 Fatty Alcohol'],
      ['Bonderite S-AD'],
    ],
  },
];

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export const brochureProducts: Product[] = groups.flatMap((group) =>
  group.names.map(([name, ...synonyms]) => ({
    slug: slugify(name),
    name,
    cas: 'Confirm with Chemstock',
    formula: 'Confirm with Chemstock',
    synonyms,
    family: group.family,
    form: 'Confirm with our team' as const,
    industries: group.industries,
    description: `${name} appears in Chemstock’s published specialty-chemicals brochure. Grade, composition, source, and current availability are confirmed on request.`,
    applications: group.applications,
    specifications: [['Current grade specification', 'Available on request']],
    source: brochure,
    identitySource: brochure,
  })),
);
